### ISSUE TITLE
play store link not working

### ISSUE THREAD

**Issue by prempalsingh** [nickbutcher/plaid#1]

**Comment by alorma** [comment]
:+1:

**Comment by nickbutcher** [comment]
Thanks for reporting. For now you can join the open beta here: plaidapp.io

**Comment by saulmm** [comment]
@nickbutcher Could you put that beta link on the Readme? Maybe could be useful for other people

**Comment by nickbutcher** [comment]
Will do.

**Comment by kabouzeid** [comment]
@nickbutcher A bit off-topic, but I just have to tell you: amazing(!) work you've done there.

**Comment by mrkma** [comment]
even after joining the group the store link doesn't work (either directly or through plaidapp.io)
