### ISSUE TITLE
App crashes at start

### ISSUE THREAD

**Issue by arkadiytehgraet** [nickbutcher/plaid#100]
The app used to be working well back some time ago, however now it crashes right at start. I do not know what  exactly the root cause is, but I manage to see the starting screen with loading progress bar. 

My device is Lenovo Vibe X2 on Android 5.0

**Comment by nickbutcher** [comment]
Hi, can you confirm that you have a Designer News source selected in the filters drawer? I'm seeing a security issue with communicating with their API on Android 5.0 devices. Thanks!

**Comment by nickbutcher** [comment]
Closing as can't replicate and no response from OP.
