### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by msay2** [nickbutcher/plaid#103]
Hello Nick Butcher

I need your help

the `ParallaxScrimageView` do this scroll not correctly

parallax does not actually execute, however works everything except the image that does not parallax

**Comment by msay2** [comment]
I changed my question @nickbutcher :)

**Comment by msay2** [comment]
Please, help me

**Comment by nickbutcher** [comment]
I'm sorry but I cannot debug every issue you have. I'd suggest adding a breakpoint to ParallaxScrimageView#setOffset and seeing what is going on. Also check your parallaxFactor attribute in your layout.

**Comment by msay2** [comment]
I was right, it was a mistake on my part, on your layout file you put a "Ripple" your "ParallaxScrimageView" in the background, while I've put an image (jpg).

in addition, you use "Glide" for a background assigned to "ParallaxScrimageView"

Here, it is because of these things that the parallax executed.

Problem resolved 

thank you for absolutely everything
:D ;)

**Comment by nickbutcher** [comment]
Glad you worked it out!
