### ISSUE TITLE
Why obtaining fontMatrices twice?

### ISSUE THREAD

**Issue by eneim** [nickbutcher/plaid#105]
[Here](https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/widget/CollapsingTitleLayout.java#L278) you get your fontMatricesInt and fontHeight again ([here](https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/widget/CollapsingTitleLayout.java#L234) was the first time) without any change in TextPaint textSize or typeFace. Just curious by is there any reason for that?

**Comment by nickbutcher** [comment]
Don't think there is a reason for this; looks like a mistake. I'm working on this class at the moment so will remove the second call. Thanks for catching this!
