### ISSUE TITLE
Designernews Articles are always 404

### ISSUE THREAD

**Issue by iashraful** [nickbutcher/plaid#106]
Version on which issue first noticed: 0.9.8

Short Description:
The Designernews articles from inside Plaid are always 404. 
There seems to be an additional "/click/" on the links generated from designer news.

Usually the links are like this: `designernews.co/stories/xxxyyy`
In recent version there is an additional "/click/" in the link like this: `designernews.co/click/stories/xxxyyy`
This results in 404.

![404_in_plaid](https://cloud.githubusercontent.com/assets/13736302/17465170/9c58ca4c-5cf0-11e6-8c2e-ecf7c331dd92.png)

![additional_click_in_plaid](https://cloud.githubusercontent.com/assets/13736302/17465173/a3a46e64-5cf0-11e6-8577-e6700d99e340.png)

![good-again](https://cloud.githubusercontent.com/assets/13736302/17465181/b6e98b76-5cf0-11e6-9b7e-ea447ab5e06e.png)

Following is a video I made of the issue.

[Video Plaid Designernews Issue](https://d17oy1vhnax1f7.cloudfront.net/items/2v2U0T3f0P1b312P1c2u/plaid_designernews_issue.mp4)

Irrelevant Note: 
I tried to upload the video but it seems to be of unsupported type + exceeds 10MB limit.

**Comment by nickbutcher** [comment]
Thanks for reporting. This seems to be an issue with Designer News; their API has always returned urls with `/click/` in the path, they just used to redirect to the actual story. This seems to have changed. I'll get in touch with them and see what's up.

**Comment by nickbutcher** [comment]
I've been in touch with Designer News and they have updated the redirect. Unfortunately it seems to now always take you to the DN discussion thread rather than the actual story. I've reported this behavior change to them.

**Comment by iashraful** [comment]
The news articles are working again today. 
You can close this issue now as it does not resolve to 404 anymore. 
Thanks for this wonderful app :heart:
