### ISSUE TITLE
ColorUtils#modifyAlpha() can be replaced with ColorUtils#setAlphaComponent() from the support library

### ISSUE THREAD

**Issue by alexjlockwood** [nickbutcher/plaid#107]

**Comment by alexjlockwood** [comment]
ColorUtils#blendColors() might be able to be replaced with ColorUtils#compositeColors() or something similar too.

I know these are super nit-picky... feel free to close. Just felt like pointing it out. :P

**Comment by nickbutcher** [comment]
Thanks for raising this, I find the [0–1] float alpha specification useful so think I'll keep this util function. I wasn't actually using `blendColors` so i've just removed it. Would have had to update it to properly gamma correct anyways to keep @romainguy happy! Thanks for the prompt!
