### ISSUE TITLE
could not be compiled

### ISSUE THREAD

**Issue by wanyt** [nickbutcher/plaid#108]
when i import the project into anroid studio in the first time, it report the error:
Error:(29, 0) CreateProcess error=2, 系统找不到指定的文件。
<a href="openFile:E:\AndroidStudio\GitHub\plaid\app\build.gradle">Open File</a>

the error occured in the build.gradle, "def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()" 

系统找不到指定的文件 --> The system could not find the file specified

**Comment by hotchemi** [comment]
@wanyt I guess you didn't clone but just download source right? It seems like shows the error which is related to execute git command.

**Comment by wanyt** [comment]
@hotchemi In fact, I clone but not download source.

**Comment by nickbutcher** [comment]
Building requires git on your path (to help automate versioning). Closing as dupe of #17.
