### ISSUE TITLE
Error:For input string: ""

### ISSUE THREAD

**Issue by jp1017** [nickbutcher/plaid#112]
Open project with Android Studio, logcat show: ------- Error:For input string: ""

**Comment by YuGoal** [comment]
I also encountered the same problem

**Comment by YuGoal** [comment]
I also encountered the same problem

**Comment by hanqingkai** [comment]
删除
def gitCommitCount = 100 +
Integer.parseInt("git --git-dir=${projectDir}/.git --work-tree=${projectDir} rev-list --count HEAD".execute().text.toInteger())
和
versionCode gitCommitCount就可以了

**Comment by nickbutcher** [comment]
Building Plaid requires git on your path (to automate versioning); closing as dupe of #17.
