### ISSUE TITLE
i can no build it,what can i do?

### ISSUE THREAD

**Issue by dedeTao** [nickbutcher/plaid#113]
def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()
def gitTag = 'git describe --tags'.execute([], project.rootDir).text.trim()
def gitCommitCount = 100 +
        Integer.parseInt('git rev-list --count HEAD'.execute([], project.rootDir).text.trim())

Error:(29, 0) CreateProcess error=2, ϵͳÕҲ»µ½ָ¶

**Comment by dedeTao** [comment]
I am not install git,I have to install it ?

**Comment by nickbutcher** [comment]
Building Plaid requires git on your path (to automate versioning); closing as dupe of #17.
