### ISSUE TITLE
Question:shrink resources

### ISSUE THREAD

**Issue by ramanbranavitski** [nickbutcher/plaid#116]
Hi I am trying to create password toggle animation like your one and have a problem in release build. With "shrink resources" option "asl_password_visibility" drawable can't be founded. In debug build everything works fine. May be you had the same problem or know what I am doing wrong? Thanks.

**Comment by nickbutcher** [comment]
I've not actually done a release build since adding this so haven't seen this issue. Perhaps the shrinker is being too aggressive; you could try using explicitly keeping the drawable with `tools:keep`:

https://developer.android.com/studio/build/shrink-code.html#shrink-resources

**Comment by nickbutcher** [comment]
Have just run into the same issue when producing a release build. Have filed [a bug](https://code.google.com/p/android/issues/detail?id=225895).

**Comment by villananda** [comment]
Sent, from my ASUS

-------- Pesan Awal --------
Dari:Nick Butcher <notifications@github.com>
Terkirim:Thu, 22 Sep 2016 22:13:03 +0700
Kepada:nickbutcher/plaid <plaid@noreply.github.com>
Subjek:Re: [nickbutcher/plaid] Question:shrink resources (#116)
