### ISSUE TITLE
if i cancel login to designer news, the maybeShowAccounts() method will be call again

### ISSUE THREAD

**Issue by Shellton** [nickbutcher/plaid#117]
that means that the AutoCompleteTextView will popup again after finishAfterTransition() was called
the suggestion following:
  add a condition: `&& isDismissing == false`  to maybeShowAccounts()'s conditions
but the must be another better way to fix this little bug. I find the getSharedElementEnterTransition was called again. i tried to call getSharedElementExitTransition().addListener , but it dosnt work. 
I have to date with my friend right now . I will try to study the new features after that. 
if you fix it with other better way ,please tell me, Thanks

**Comment by nickbutcher** [comment]
Fixed by 0c5e0cb
