### ISSUE TITLE
Create Hacktoberfest label and add them to issues

### ISSUE THREAD

**Issue by danielgomezrico** [nickbutcher/plaid#129]
Hi guys,

Will be great if this project can be part of

https://hacktoberfest.digitalocean.com/

**Comment by Jawnnypoo** [comment]
Just FYI, you can make a PR on any repo in GitHub to participate in hacktoberfest, it does not need to have the label.

**Comment by nickbutcher** [comment]
Thanks for the suggestion but think I'll pass.
