### ISSUE TITLE
InkPageIndicator draws long black line

### ISSUE THREAD

**Issue by lawloretienne** [nickbutcher/plaid#130]
So I really like the indicator you have created `InkPageIndicator` but I noticed an issue with it.  If you scroll a `ViewPager` very quickly the `InkPageIndicator` draws a long black line on the screen.

I have created a short video demonstrating the issue
https://goo.gl/photos/16U2qaQjvge8q6gcA

The issue shows up at 6 seconds into the video.  The `InkPageIndicator` is at the bottom of the screen.

**Comment by nickbutcher** [comment]
Scrubbing ancient bugs. Please reopen if this is still an issue.
