### ISSUE TITLE
DribbbleShot#expandImageAndFinish() and transition animation issue

### ISSUE THREAD

**Issue by lzanita09** [nickbutcher/plaid#14]
I noticed that the transition animation was off when the ListView is scrolled up. Specifically, when the `commentList` is scrolled to bottom and I finish the activity, the ImageView seemed to expand to the original position, and it was transition back to a wrong position in the RecyclerView, where the image is cut off, and eventually the image jumped back to the correct position. An example is the gif below:

![transition_animation_issue](https://cloud.githubusercontent.com/assets/1761573/10867239/2a1109fe-8014-11e5-82fe-72e3276ecdcf.gif)

I checked the code in `DribbbleShot#expandImageAndFinish()`, the animation brings the ImageView back to `offset = 0`, but that doesn't seem to be enough to adjust the transition animation.

To work around it, I tried scrolling the `commentList` back to position 0 before finishing the activity, and it is working quite well. All I did was using `commentsList.smoothScrollToPosition(0);` instead of the ObjectAnimation. To make things smoother, you can also add a slight delay on calling `finishAfterTransition()`.

**Comment by nickbutcher** [comment]
Fixed by f98b8769f2d447bc40bf6ce7b1531ebf10da795f
