### ISSUE TITLE
SpannedGridLayoutManager problem

### ISSUE THREAD

**Issue by jaumard** [nickbutcher/plaid#155]
Hi ! 

I'm trying to use your SpannedGridLayoutManager on my project but I have some problems with it and can't find where is the problem.

I have two problems : 

- First, if I set columns to 1 or 2 it crash when scrolling down and then up and show only 3/20 items :( 
- Second, depends of the span configuration sometime there some overlapping between items

I create a small project to show you both problem here https://github.com/jaumard/SpannedGridLayoutManager 

You can toggle to first issue to the second be changing the number of columns here https://github.com/jaumard/SpannedGridLayoutManager/blob/master/app/src/main/java/com/jaumard/gridlayoutmanager/MainActivity.java#L45

Can you help me ? Or show me the way on how I can fix those problems.
Thanks for your work ! You should consider creating a small library with your SpannedGridLayoutManager :) it can be very useful

**Comment by birjubhatt** [comment]
hi

i have same problame 

    private final int DEFAULT_COLUMN = 5;

 if (position == 0 | position == 3) {
                        return new SpannedGridLayoutManager.SpanInfo(3, 3);
                    } else {
                        return new SpannedGridLayoutManager.SpanInfo(2, 2);
                    }

i have more then 50 data......in <5 its works fine but when more data is come from server its crash 

and i cant change my condition or span info paramiter ...because its effect my design......so i only want crash solve suggation (without changes my condition or return values) or give me suggation or answer who match my condition ...thanks

**Comment by otokajo** [comment]
Hi !

I'm trying to use your SpannedGridLayoutManager on my project but I have some problems with it and can't find where is the problem:
SpannedGridLayoutManager not working the data size <2

**Comment by AhmedNourShahorur** [comment]
> Hi !
> 
> I'm trying to use your SpannedGridLayoutManager on my project but I have some problems with it and can't find where is the problem:
> SpannedGridLayoutManager not working the data size <1



> Hi !
> 
> I'm trying to use your SpannedGridLayoutManager on my project but I have some problems with it and can't find where is the problem:
> SpannedGridLayoutManager not working the data size <1
i have the same problem ..... 
did you solve it ?

**Comment by ataulm** [comment]
`SpannedGridLayoutManager` doesn't exist in this project. 

I went back as far as Aug 2016 but couldn't find any references to this class.
Suggest closing this issue as it doesn't seem to be related to this project (at least anymore).

**Comment by Xinng** [comment]
@ataulm FYI: https://github.com/android/plaid/blob/6a3cb17ede0ffeffb4ca16e4fd3c2ab60900d6b8/app/src/main/java/io/plaidapp/ui/recyclerview/SpannedGridLayoutManager.java
