### ISSUE TITLE
App Shortcut Icon creation

### ISSUE THREAD

**Issue by niteshvuliv** [nickbutcher/plaid#159]
Hi. I am implementing app shortcuts in one of my project, however, I am having trouble generating those icons' vector drawables. I want a music note (#FF0000) inside the circle (#F5F5F5).

I don't know how to proceed and put the music note inside circle with padding all around it. The icon I am creating have the note at the top-left corner. I don't know what path should I write to draw it in the centre. 

Kindly help me out.

    <vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="48dp"
    android:height="48dp"
    android:viewportWidth="48"
    android:viewportHeight="48">

    <path android:fillColor="#f5f5f5"
        android:pathData="M24,24m-22,0a22,22 0,1 1,44 0a22,22 0,1 1,-44 0" />

    <path android:fillColor="#FF0000" android:pathData="M12,3V12.26C11.5,12.09 11,12 10.5,12C8,12 6,14 6,16.5C6,19 8,21 10.5,21C13,21 15,19 15,16.5V6H19V3H12Z" />

    </vector>

**Comment by nickbutcher** [comment]
Here you go (I created it in Sketch, exported as SVG and then imported into Android Studio):

```
<vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="48dp"
    android:height="48dp"
    android:viewportWidth="48"
    android:viewportHeight="48">
  <path
      android:pathData="M24,24m-22,0a22,22 0,1 1,44 0a22,22 0,1 1,-44 0"
      android:fillColor="#F5F5F5"/>
  <path
      android:pathData="M24,14L24,24.55C23.41,24.21 22.73,24 22,24C19.79,24 18,25.79 18,28C18,30.21 19.79,32 22,32C24.21,32 26,30.21 26,28L26,18L30,18L30,14L24,14Z"
      android:fillColor="#FF0000"/>
</vector>
```

**Comment by niteshvuliv** [comment]
Thank you very much
