### ISSUE TITLE
Password entry animation with San-Serif

### ISSUE THREAD

**Issue by ozv101** [nickbutcher/plaid#162]
The password entry animation works well with the default, monospace, typeface. However, if switch it to san-serif, so it matches my other EditTexts, the animation doesn't work because the dot doesn't take up the same width as a character. How would I modify the draw method so it draws it correctly with san-serif?

**Comment by nickbutcher** [comment]
You'll have to modify the [`PasswordCharacter`](https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/widget/PasswordEntry.java#L255) class to work for non-monospace fonts. Specifically you can't [use the index to calculate the x position](https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/widget/PasswordEntry.java#L280). You'll likely have to track the x position of each character in each state.

Good luck, i'm closing this bug as it's not an issue with Plaid.
