### ISSUE TITLE
CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by Jaydeep00** [nickbutcher/plaid#165]

**Comment by nickbutcher** [comment]
Please can you provide more info on this issue and steps to reproduce.

**Comment by imneeraj** [comment]
I'm also getting the same error while the project is building.
In app/build.gradle :' def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()'

**Comment by nickbutcher** [comment]
Building Plaid required `git` on your path. Closing as dupe of #17
