### ISSUE TITLE
Your plans for the future

### ISSUE THREAD

**Issue by sergeyfitis** [nickbutcher/plaid#166]
@nickbutcher Have you any plans do more features for the app in the nearest future? Enhance the app or make completely new design, etc. Thank you.

**Comment by nickbutcher** [comment]
Hi there. I do have a few ideas but noting imminently planned. Is there something you'd like to see or contribute?

I should probably file issues to track the enhancements i've not gotten to yet…

**Comment by FabianTerhorst** [comment]
A working SpannedGridLayoutManager would be awesome.

**Comment by nickbutcher** [comment]
I've filed #174 to track this; please do file issues for anything you'd like to see so we can discuss them individually. Closing this issue.
