### ISSUE TITLE
Fix Designer News!!

### ISSUE THREAD

**Issue by nickbutcher** [nickbutcher/plaid#175]
Looks like the v1 API no longer works. Guess it's time to move to v2.

**Comment by eneim** [comment]
@nickbutcher Any luck to get latest beta release from Play Store with this fix?

**Comment by piotrek1543** [comment]
there already PR according to this issue: https://github.com/nickbutcher/plaid/pull/179

@eneim could you check if it's working properly?

**Comment by nickbutcher** [comment]
@eneim sorry no, this is still outstanding.

@piotrek1543 please don't assign tasks to people on this repo.

**Comment by nickbutcher** [comment]
Now being worked on as part of https://github.com/nickbutcher/plaid/projects/1. Closing this bug in favor of more granular ones.
