### ISSUE TITLE
BaselineGridTextView lineHeightHint difference

### ISSUE THREAD

**Issue by krokyze** [nickbutcher/plaid#176]
Hi,

lineHeightHint in xml as 20sp - getDimensionPixelSize == 53
lineHeightHint in xml as 20sp - getDimension == 52.5
programmatically - 20 * resources.displayMetrics.scaledDensity == 52

The problem is that computeLineHeight for value 53 calculates baselineAlignedLineHeight as 62, but when I set lineHeight programmatically for value 52 the baselineAlignedLineHeight stays 52.

So in the end which should be the right value for line height? 52 or 62?

**Comment by nickbutcher** [comment]
Thanks for raising this, hopefully the fix will resolve this issue for you by retaining precision for as long as possible.

Incidentally this

> programmatically - 20 * resources.displayMetrics.scaledDensity == 52

…is not correct. I assume you're casting to an int at some point to get that value? If so you should always round up (thus the `+ 0.5f` in my fix) when converting to discrete pixel values (see [TypedValue](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/util/TypedValue.java#303) for the source of truth).

**Comment by krokyze** [comment]
Hi, yes I was using one of Anko methods: 
fun Context.sp(value: Int): Int = (value * resources.displayMetrics.scaledDensity).toInt()

I applied your fix and remove casting to an int, now everything looks awesome. Thanks for your fast response.
