### ISSUE TITLE
Change ElasticDragDismissFrameLayout scrolling functionality

### ISSUE THREAD

**Issue by rLinks234** [nickbutcher/plaid#182]
This may seem a bit nitpicky, but it feels like the current implementation of ElasticDragDismissFrameLayout is a bit counter intuitive to touch events. Specifically, if there are multiple pointers down (fingers), any movement from any pointer can cause the view to move up or down. To me, it seems more logical for the view to move only if there is 1 pointer down.

While this is a bit of a hack (it probably doesn't cover every touch event usecase), it seems a bit better when the following is added to ElasticDragDismissFrameLayout:

```
public class ElasticDragDismissFrameLayout extends FrameLayout {

    ...

    private int currentPointerCount;

    ...

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        currentPointerCount = ev.getPointerCount();
        return super.onInterceptTouchEvent(ev);
    }

    @Override
    public boolean onStartNestedScroll(View child, View target, int nestedScrollAxes) {
        return (nestedScrollAxes & View.SCROLL_AXIS_VERTICAL) != 0
            && currentPointerCount == 1;
    }

}
```

**Comment by nickbutcher** [comment]
Thanks for raising an interesting point; I however disagree. 

I consider the touch handling the concern of the scrolling view and this is how the default scrolling widgets treat multiple pointers. I don't consider this a concern of `EDDFL` and like that it simply responds to the scrolling view.

You're obviously more than welcome to create a fork with this behaviour and again thanks for raising the issue.
