### ISSUE TITLE
ElasticDragDismissFrameLayout scrolling too far on fast scroll gesture

### ISSUE THREAD

**Issue by HaukeRa** [nickbutcher/plaid#185]
I encountered a strange Issue while working with the ElasticDragDismissFrameLayout

Everything works fine while scrolling in the content and then dragging it over its bounds (so that events having dyUnconsumed !=0 are generated).

But whenever the containing ScrollView is already scrolled all the way up or down and when I'm doing a fast scroll motion results in the ElastigDragDismissFrameLayout beein scrolled way further than it should be. The issue here is, that if one returns to the starting point of the scroll motion, the view is not at its starting position, and is dismissed when stopping the scroll gesture.

Here are three examples, rawOffsetPixels of onDrag(..) is displayed in the corner:

[https://drive.google.com/open?id=0BxJvibam28UTcER0dXZ6c3I1a0k](url)
Notice how rawOffsetPixels is reported as 3207 pixels, whereas the touch tracker from the android developer settings reports a total dY of 1761 pixels.

[https://drive.google.com/file/d/0BxJvibam28UTaTBrZW9wVURJQXc/view?usp=sharing](url)
Starting the scroll fast and returning to the starting point of the scroll, rawOffsetPixels is still about 750 pixels.

[https://drive.google.com/file/d/0BxJvibam28UTQmdGamI2SDlPRWc/view?usp=sharing](url)
When starting the scroll slower, everything works as intended

My guess what is happening is that there is a conflict between setting translationY and the reported onNestedScroll(..., dyUnconsumed). There might be a race condition, where setting the translation will result in another onNestedScroll(..) being fired, with a dyUnconsumed value higher as it should be.

While less severe, i also could find this behaviour in the Plaid app, especially when scrolling over the end at bottom. I guess this somehow depends on layout complexity or main thread activity.

I will investigate further, maybe a separate transparent ScrollView can be used that is not translated/scaled but sends the scroll events to the inner ScrollView.

**Comment by AllanWang** [comment]
I've tried this with RecyclerViews and it seems to work fine so long as the touch starts within the RecyclerView where an item exists in the adapter. When the jump occurs, logging the dy dispatched from the nested children does show extreme values (~100 vs ~20), so it may be an issue within the support library.

**Comment by castorflex** [comment]
Hey there,
As you can see in [this video][YT], the effect seems even stronger using animation duration scale x10 for some reasons ...

[YT]: https://youtu.be/t-kYvsXIDoM

**Comment by castorflex** [comment]
I think I found the issue here:
`View#dispatchTouchEvent(MotionEvent)` will call `stopNestedScroll()` when `actionMasked == MotionEvent.ACTION_DOWN`, meaning `ElasticDragDismissFrameLayout#onStopNestedScroll()` will be called, resulting in the call of the 'returning' animation. That's probably why the effect is even uglier using animation duration scale x10.

By removing the animation and just set `setTranslationY(0);` the bug disappear, but, of course, the returning animation too. Hopefully I will come with a clean fix today.

Cheers
