### ISSUE TITLE
Search engine

### ISSUE THREAD

**Issue by Adikot** [nickbutcher/plaid#189]
After entering one of the results, when I go back to the search page- the keyboard keeps on opening though I only wanted to get inside another result page. It is not fun. 

Nevertheless, I wanted to congratulate you, I am using this app for quiet some time now and I keep on getting back to in, so it means it is useful to me, so it's awesome :) thank you!

**Comment by nickbutcher** [comment]
Thanks for reporting this issue and glad that the app is useful to you :D
