### ISSUE TITLE
Third line of text in home grid is cut on Nexus 4

### ISSUE THREAD

**Issue by Zhelyazko** [nickbutcher/plaid#19]
The third line of text on the home screen grid is cut in half on Nexus 4 running stock Android 5.1.
See screenshot:
![nexus_4_grid](https://cloud.githubusercontent.com/assets/815465/10877496/5f1efc46-814f-11e5-812b-32f3bfbfa9b9.png)

**Comment by Olric86** [comment]
I have the same problem both on a Nexus 5 and on a Nexus 6p.
It looks like the issue is triggered by selecting 'small' as default text size in the Android Settings.

![screenshot_20160121-141713](https://cloud.githubusercontent.com/assets/1961744/12481674/fa185f32-c04a-11e5-8366-3f8a0dcefc0f.png)

**Comment by walmyrcarvalho** [comment]
Have the same issue on the Nexus 5 as well. Besides that, the app is amazing. <3
