### ISSUE TITLE
Migration to kotlin

### ISSUE THREAD

**Issue by erluxman** [nickbutcher/plaid#190]
What are the plans about migrating the project to kotlin ? Can people contribute some kotlin migration?

**Comment by nickbutcher** [comment]
I don't have plans to migrate the whole app to kotlin any time soon but will likely do any new work in Kotlin and convert existing files as I touch them.

More than happy to look at Kotlin PRs.

**Comment by AllanWang** [comment]
Are you still interested in kotlin conversions? I have some files that I've ported to my project that are rewritten in kotlin. And if so, which branch should we base off of and submit to?

**Comment by piotrek1543** [comment]
@nickbutcher I think that good idea would be to create a branch named `kotlin` for future contributions like it was about two weeks ago in android-topeka repo - there were two branches - master (Java) and kotlin.

**Comment by nickbutcher** [comment]
Kotlin support has already been merged into the project (#194). There are no plans for a mass migration so a separate branch isn't appropriate, just submit PR to `main`.

Closing this issue as there's nothing to do here.

**Comment by piotrek1543** [comment]
@nickbutcher ok, I understand.
