### ISSUE TITLE
Move to Glide 4

### ISSUE THREAD

**Issue by nickbutcher** [nickbutcher/plaid#191]
See https://github.com/bumptech/glide

Also investigate plugging in [Rastermill](https://github.com/android-ia/platform_frameworks_ex/tree/master/framesequence/) for GIF decoding.

**Comment by piotrek1543** [comment]
I think you can split this into two issues, first for Glide, and second one for Rastermill. It might be more clear ;-)

I've created a MR with updated dependencies: https://github.com/nickbutcher/plaid/pull/196

Nowadays, Glide4 is in 'RC1' version state and missing some functions like DrawableRequestBuilder.

I don't see how to change it. Maybe in final version they would give it back ;-)

**Comment by franciscofranco** [comment]
I strongly suggest https://github.com/koral--/android-gif-drawable for Gifs. I believe that's what Google+ app uses. It's miles faster than Glide.

**Comment by nickbutcher** [comment]
Thanks for the suggestions @franciscofranco, good to know. I'm breaking out the perf issue as #203 to focus this issue on the Glide migration.
