### ISSUE TITLE
Nested Scrolling has small blips in ElasticDragDismissFrameLayout

### ISSUE THREAD

**Issue by AllanWang** [nickbutcher/plaid#193]
If the frame layout contains a scroll view, as in the first page in the about overlay, pulling down really fast will cause the scrollview to suddenly jump down. Doing it slowly is fine, and it works on the library page where it's a recyclerview. Not exactly sure how to address that.

**Comment by HaukeRa** [comment]
I face the same issue (see https://github.com/nickbutcher/plaid/issues/185)

**Comment by nickbutcher** [comment]
Yes this looks like #185, lets close and continue there.
