### ISSUE TITLE
SearchBack Animation

### ISSUE THREAD

**Issue by confusedCoder223** [nickbutcher/plaid#197]
First off, I love the design of this app and appreciate that the code is here for anyone to learn from. I am having an issue when I tried to implement the search to back button animation. Everything else works fine, but when the button moves after pressing it (the shared element transition), the animation shows it going past where the arrow is in the search activity. Do you know what might be causing it?

**Comment by nickbutcher** [comment]
Thanks! Can you post a video/gif of what you're seeing?

**Comment by confusedCoder223** [comment]
Thanks for responding. Here is a video of what is happening.
![ezgif-3-0feb12f5f2](https://user-images.githubusercontent.com/30380238/28696838-24036804-7306-11e7-8c9f-dbacdd8b6dc7.gif)

**Comment by nickbutcher** [comment]
Hmmm, the icon movement is just a standard `ChangeBounds` transition. I'd try placing a break point in it's capture values methods and investigate what is going on.

**Comment by confusedCoder223** [comment]
I've placed breakpoints in the methods, but I don't really know what I am looking for. What would be telltale of something going wrong?

**Comment by confusedCoder223** [comment]
I solved the issue. I just deleted and rewrote all of the files and now it works as intended.

**Comment by GauvainSeigneur** [comment]
Just for information, I had the same issue. Is just because I set app:srcCompat to ImageButton and not Android:src.

For those who want compatibility with lower API, I suggest to define two different layout for the toolbar.
