### ISSUE TITLE
Dribbble 'Liker' list should feature elevation

### ISSUE THREAD

**Issue by stoyicker** [nickbutcher/plaid#202]
When tapping the heart on top of the amount of likes on the detail view for a Dribbble item, the list that appears from the bottom and that will eventually take over the whole screen height does not feature elevation in addition to the fullscreen shade that covers what becomes the 'background' to give 'modality' to the list.
As far as I understand, the lack of elevation creates an impression that goes against the following excerpt from https://material.io/guidelines/material-design/elevation-shadows.html:
> In the physical world, objects can be stacked or affixed to one another, but cannot pass through each other.
Should this be corrected, or is it intended?

**Comment by nickbutcher** [comment]
It actually does. See:

https://github.com/nickbutcher/plaid/blob/master/app/src/main/res/layout/player_sheet.xml#L31

It's kinda subtle as the key light in material is top down i.e. to top of the sheet doesn't cast much of a shadow.
