### ISSUE TITLE
Explanation?

### ISSUE THREAD

**Issue by Obaied** [nickbutcher/plaid#220]
Hey. My apologies in advance. This is not really an issue but more of a question. I honestly, truly have had a very, very hard time understanding the interactions and details of all of those animations.

Is there anywhere someone can recommend to learn more about how these animations are made?

**Comment by nickbutcher** [comment]
Which kind of animation are you talking about?

For an overview of all of the animation APIs on Android, check out [this conference talk](https://skillsmatter.com/skillscasts/6798-meaningful-motion). If it's the icon animation then I'd check out [this amazing blog post](http://www.androiddesignpatterns.com/2016/11/introduction-to-icon-animation-techniques.html). If it's the transitions then perhaps [this I/O talk](https://www.youtube.com/watch?v=4L4fLrWDvAU).

**Comment by Obaied** [comment]
That's a good starting point. Much appreciated :)
