### ISSUE TITLE
Transition Duration Overrides Attached Animator Durations

### ISSUE THREAD

**Issue by Obaied** [nickbutcher/plaid#221]
Hey

From what I can see in this doc, a duration for `Transition` would override any attached animator durations
https://developer.android.com/reference/android/transition/Transition.html#setDuration(long)

This would nullify the durations assigned for the separate animators in the `FabTransform.java` class over here: https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/transitions/FabTransform.java#L158

I just wanted to get an understanding if I missed something before going through with a PR. Thanks in advance!

**Comment by nickbutcher** [comment]
Yes if you set a duration on a `Transition` it will overwrite the `Animator`s duration. See https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/transition/Transition.java#1865

Also adding `Transition`s to a `TransitionSet` can overwrite durations:
https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/transition/TransitionSet.java#146
https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/transition/TransitionSet.java#186
