### ISSUE TITLE
Fail build

### ISSUE THREAD

**Issue by seakleng016** [nickbutcher/plaid#232]
After i clone and build , i get this message
Error:Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to find byte code for android/util/IntProperty

**Comment by nguyenhuutinh** [comment]
[Workaround]
in io.plaidapp.util.AnimUtils
remove IntProperty and FloatProperty block
public static <T> Property<T, Integer> createIntProperty(final IntProp<T> impl)
 public static <T> Property<T, Float> createFloatProperty(final FloatProp<T> impl)

**Comment by LoveqLRC** [comment]
The problem will go away if I change this:
```
public class AnimUtils { ... }
```
to
```
@TargetApi(Build.VERSION_CODES.M)
public class AnimUtils { ... }
```

**Comment by nickbutcher** [comment]
🤷‍♂️ I can't replicate this issue. If you can provide steps to reproduce then please re-open.

**Comment by amilcar-andrade** [comment]
@nickbutcher I think that some packages are not available yet to download. Maybe some of them are still internal and only available for Google employees. 

@nguyenhuutinh is right if you remove the use of `IntProp` and `FloatProp` then the build works without a problem. I also saw this when I fetched the latest changes.

**Comment by seakleng016** [comment]
thank you all . now it working after remove instant run

**Comment by nickbutcher** [comment]
@amilcar-andrade not sure what you mean, we doesn't use any private packages? [IntProperty](https://developer.android.com/reference/android/util/IntProperty.html) is public API. `IntProp` is my wrapper class to use on older APIs.

**Comment by amilcar-andrade** [comment]
Oh yeah, you are right. I thought it was a private one. Sorry!

**Comment by rcd27** [comment]
It can be also "fixed" by turning off the `Instant Run` in Android Studio.

**Comment by AhujaSourabh** [comment]
Failed to find byte code for com/google/android/exoplayer2/decoder/PictureOutputBufferManager
