### ISSUE TITLE
PlayerActivity content on landscape mode not easily accessible

### ISSUE THREAD

**Issue by amilcar-andrade** [nickbutcher/plaid#233]
Sometimes the content is not accessible and cannot be scrolled. See below image.
<img width="1321" alt="screen shot 2017-12-02 at 4 45 25 pm" src="https://user-images.githubusercontent.com/802308/33521202-6153c7f6-d780-11e7-9916-7e6ff3261983.png">

I have a proposal for this issue. Please look at the UI and video and let me know if a PR would be a good idea for this.

Thanks!
![screenshot_20171202-163618](https://user-images.githubusercontent.com/802308/33521210-a0630bfa-d780-11e7-8642-654a56cf4096.png)

https://www.youtube.com/watch?v=oBQ7dVL_Q90

**Comment by nickbutcher** [comment]
Nice - I like it. Some questions:
- We'd want to control the number of columns based on the width of the grid, not the overall screen width (3 looks too tight here). I'd be nice if this could reuse the existing qualifiers somehow.
- It'd be nice to cap the width of the profile info, i.e. on tablets half width might be too much.

**Comment by amilcar-andrade** [comment]
Sounds good I will give it a try. I think I know how to achieve both.

**Comment by florina-muntenescu** [comment]
Feature not available anymore
