### ISSUE TITLE
HomeActivity OptionsMenu not animated 

### ISSUE THREAD

**Issue by weikano** [nickbutcher/plaid#24]
1. It's not the right time to get ActionMenuView during onCreate, since the OptionsMenu may not be created .
2. toolbar.getChildAt(1) doesn't return ActionMenuView, maybe you should find ActionMenuView recursively from Toolbar.
3. Animate the ActionMenuView during onPrepareOptionsMenu maybe a better choice. With a boolean flag indicates whether ActionMenuView has been animated or not.
4. Save that boolean flag when onSaveInstanceState and restore them so the menu won't animate after rotate screen.

**Comment by nickbutcher** [comment]
Thanks for the comments.  There is some dead code in there, previously I was using a `Toolbar` (without calling `setActionBar`) which allowed me to animate the items.  I had to remove this as currently there is no way to update the menu contents like you can with `onPrepareOptionsMenu` which I need to correctly configure the log in/out menu items.

I should probably just remove this code… unless you want to submit a PR with your proposed solution?
