### ISSUE TITLE
error: cannot find symbol method fitCenter()

### ISSUE THREAD

**Issue by amineallam** [nickbutcher/plaid#247]
hi i'm new here ..
i'm having  an issue with the Title Above  error: cannot find symbol method fitCenter()
at this code 
`@Override
    public void onBindViewHolder(ViewHolder holder, final int position) {
        final TemplateListModel item = items.get(position);
        holder.image.setImageBitmap(null);
        int imageResource = mGallaryCollageActivity.getResources().getIdentifier(item.getImage(), null, mGallaryCollageActivity.getPackageName());
        //Picasso.with(mContext).load(item.getImage()).into(holder.image);
        holder.itemView.setTag(item);
        Glide.with(mGallaryCollageActivity).load("file://" + item.getImage()).fitCenter().into(holder.image);`

my build.Gradle File is like 
`
dependencies {
    compile 'com.android.support:support-v4:27.0.2'
    compile 'com.android.support:design:27.0.2'
    compile 'com.android.support:appcompat-v7:27.0.2'
    compile 'com.android.support:cardview-v7:27.0.2'
    compile 'com.android.support:recyclerview-v7:27.0.2'
    compile 'com.android.support:percent:27.0.2'
    compile 'com.github.armcha:LuseenBottomNavigation:1.8.2'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.4'
    compile 'com.google.android.gms:play-services-ads:11.8.0'
    compile 'com.github.bumptech.glide:glide:4.5.0'
    compile files('libs/picasso-2.3.4.jar')
    compile files('libs/pinchzoom.jar')
}`
& 
my project Gradle 
` 
buildscript{
    repositories {
        mavenCentral()
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.0'

    }`
any help will be appreciated ? thanks in advance

**Comment by nickbutcher** [comment]
This method comes from Glide. I recommend you check their docs out to ensure you're setting it up correctly. https://github.com/bumptech/glide
