### ISSUE TITLE
InstantRun sopport issue

### ISSUE THREAD

**Issue by rcd27** [nickbutcher/plaid#250]
Unable to build project:
`Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to find byte code for android/util/IntProperty`

Disabling InstantRun feature in AndroidStudio3.0.1 solves this.

**Comment by nickbutcher** [comment]
Same as #232?

**Comment by rcd27** [comment]
Yes, my apologies.
