### ISSUE TITLE
  SpannedGridLayoutManage

### ISSUE THREAD

**Issue by heapsol** [nickbutcher/plaid#260]
Hello nick how are you ??

Can you tell me where i can find your   SpannedGridLayoutManage class ???

@nickbutcher

**Comment by nickbutcher** [comment]
It's on the `grid_span` branch: https://github.com/nickbutcher/plaid/blob/grid_span/app/src/main/java/io/plaidapp/ui/recyclerview/SpannedGridLayoutManager.java
