### ISSUE TITLE
gradle build failed

### ISSUE THREAD

**Issue by hellworld** [nickbutcher/plaid#27]
import the project to Android Studio 1.5beta

gradle build 

Error:(23, 0) For input string: ""
<a href="openFile:C:\Users\Administrator\Desktop\plaid-master (1)\plaid-master\app\build.gradle">Open File</a>

**Comment by BillBosiolis** [comment]
On Ubuntu, with Git installed (and being on the path) I had no problem to open the project in Android Studio and build it successfully.

On Windows, I was getting the known error (20 - CreateProcess error=2). Here's what I did to solve it

1. Installed a newer Git version (I don't think it has to do anything with the version, I just wanted to modify the installation)
2. In the "Adjusting your Path environment" step I selected the second option - Run Git from the Windows Command Prompt
3. Restarted Studio and set the the path to the git executable. Settings -> Version Control -> Git and set it "C:\Program Files\Git\cmd\git.exe".

Hope that it helps
