### ISSUE TITLE
Shared Element transition issue

### ISSUE THREAD

**Issue by SoftXperience** [nickbutcher/plaid#28]
When I click on a DribbleShot, the preview image is animated to the header image in details screen.
On Samsung S5, the image bounds seems not to change and the small preview image goes to the top left on screen. Afterwards it pops to full size, if the image was not loaded (cached) before.
![ezgif-1618060153](https://cloud.githubusercontent.com/assets/8452407/10938438/860b90e2-82fa-11e5-8d23-81e58770bd54.gif)
If the details were opened before (so the image was cached), the image stays in the top left corner.
![ezgif-3007249193](https://cloud.githubusercontent.com/assets/8452407/10938484/ea9921f0-82fa-11e5-9dba-9ad7516fc427.gif)
It seems to be an issue with glide and/or caching, but happens to me only on the Samsung S5 (Android 5.0, Build LRX21T.G900FXXU1POFE)

I'm running into the same issue in my app, hope you have an idea to fix it.

**Comment by petersnoopy** [comment]
+1

**Comment by SoftXperience** [comment]
I renamed the issue because it also happens on other devices like Motorola Moto E with Android 5.0.2, not only on Samsung devices.

**Comment by nickbutcher** [comment]
I think that this is an issue with Lollipop as it seems to work correctly on newer devices. Unlikely to get to this so marking as won't fix. :(
