### ISSUE TITLE
[CI] Code formatting

### ISSUE THREAD

**Issue by nickbutcher** [nickbutcher/plaid#302]
PRs are getting noisey due to formatting differences. We should check in a formatter and run over the entire project.

**Comment by tiembo** [comment]
Related to #288

**Comment by nickbutcher** [comment]
Also field/annotation order/line breaking: https://github.com/nickbutcher/plaid/pull/331#discussion_r197653732

**Comment by nickbutcher** [comment]
Related to #329 (in that for both we need to pick a format) but not a dupe.  This is more about checking in the Android Studio formatter so that everyone is running the same thing plus running over the entire codebase to reduce PR noise.

**Comment by tiembo** [comment]
I think #345 and #346 fixes this issue.
