### ISSUE TITLE
An error occured while executing doInBackground()

### ISSUE THREAD

**Issue by AversonCoder** [nickbutcher/plaid#32]
just start app

![RuntimeException](https://cloud.githubusercontent.com/assets/13031684/11015524/f62d2c10-859c-11e5-807c-1de033dab44c.png)

**Comment by nickbutcher** [comment]
Can you confirm which version of the app you are seeing this in? I thought this was fixed by 3abea4d2e4b5b7ac0a8d1ce80cabc4052c21a3dc in 0.4.1

**Comment by AversonCoder** [comment]
Thank you, I'll look in detail

**Comment by nickbutcher** [comment]
Can you confirm that this is resolved for you as i'd like to close this out.  Thanks!
