### ISSUE TITLE
Status bar only changes in landscape

### ISSUE THREAD

**Issue by personesk** [nickbutcher/plaid#36]
Nexus 6 running stock Marshmallow

![screenshot_20151109-122407](https://cloud.githubusercontent.com/assets/15744470/11045613/4abb744e-86dd-11e5-8f43-538cc0024d54.png)
![screenshot_20151109-122414](https://cloud.githubusercontent.com/assets/15744470/11045612/4ab9e91c-86dd-11e5-8585-0e1b625e1229.png)

**Comment by nickbutcher** [comment]
Thanks for the report. I've not tested on a N6 for a while; I'll investigate tomorrow. 

If you rotate back to portrait do you lose the light-status-bar? 

Also please can you confirm the exact build you are running?

**Comment by Jawnnypoo** [comment]
Seeing the same thing on a Nexus 6P. Is NOT a light status bar when you switch back to portrait, only light when in landscape. On the latest Beta Play Store build for me. (0.5)

**Comment by personesk** [comment]
It stays dark grey in portrait, even after rotating to landscape. The app is v0.5 and my N6 is running MRA58K

**Comment by nickbutcher** [comment]
Thanks for the bug reports.  This is working correctly on my Nexus 5X so i'm pretty sure the app code is correct and that this is an issue with those devices.  I'll investigate further.

**Comment by nickbutcher** [comment]
Actually I take it back.  This is related to #2; it is also caused by a bug in Palette. 9c6468a6430f9b4f2ad8a5da96abd4a341c8dcc8 works around this and also fixes this issue.
