### ISSUE TITLE
Why moving away from git tag on VersionName

### ISSUE THREAD

**Issue by xlagunas** [nickbutcher/plaid#387]
Hi guys, I took inspiration of you to automate versionName in my app and so far I'm happy with it. 

Now, watching #372 you moved away from it. Can you share how are you going to automate it from now on? Seems to me that manually updating is a step back on automating. Was there any drawback to using your previous approach? Thanks

**Comment by nickbutcher** [comment]
Just wanted to make versioning more explicit & collaborative (i.e. for there to be a PR bumping it) as a step toward being able to release from CI to enable CD. If the previous tag system works for you then that's great. I don't see it as less automated, we're switching one manual process (applying a tag and pushing it) for another (bumping the version in a PR).
