### ISSUE TITLE
archivesBaseName in build.gradle of app module

### ISSUE THREAD

**Issue by gokhanbarisaker** [nickbutcher/plaid#41]
What is the purpose of `archivesBaseName` in build.gradle of app module?

**Comment by gokhanbarisaker** [comment]
This issue can also be extended for `GIT_SHA` variable that is added to `buildConfigField`. Seems like both (`archivesBaseName` & `GIT_SHA`) variables are not being used in the project.

**Comment by nickbutcher** [comment]
Hi @gokhanbarisaker, `archivesBaseName` is a gradle convention for setting the name of the output file. I use this to customise the file name, e.g. to `plaid-0.5.5-release.apk`.  See the [gradle docs](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.BasePluginConvention.html#org.gradle.api.plugins.BasePluginConvention:archivesBaseName) for more info.

The `GIT_SHA` build config isn't currently being used. I made that available as it can be extremely useful for crash reporting (see [this great article](http://www.donnfelker.com/why-you-should-use-a-git-sha-in-your-crash-reporting/)).  It _could_ be removed but I don't see any point in doing so as it might be useful in the future and it's nice to demonstrate this technique.

**Comment by gokhanbarisaker** [comment]
Awesome trick, thanks :+1:

**Comment by agrvaibhav** [comment]
@nickbutcher How can you add `buildFlavor` in `archivesBaseName`? Can you share how did you configure that?

**Comment by ataulm** [comment]
```groovy
android {
    ...

    defaultConfig {
        ...
        archivesBaseName = 'myDefaultName.'
    }

    // Specifies one flavor dimension.
    flavorDimensions "version"
    productFlavors {
        full {
            versionNameSuffix "-full"
        }
        demo {
            versionNameSuffix "-myDemoSuffix"
        }
    }

    variantFilter { variant ->
        def name = variant.flavors*.name
        archivesBaseName = 'my-flavor-name-is-' + name + '-awesome'
    }
    ...
```

![image](https://user-images.githubusercontent.com/2678555/50206865-acaad300-0364-11e9-8717-9bb4fd1f1781.png)


You can override `archivesBaseName` anywhere in the `android` block. `versionNameSuffix` can already be used to differentiate between APKs generated for different flavors, but you can have more control if you like by setting `archivesBaseName` in the `variantFilter` function.
