### ISSUE TITLE
upgrade to 1.5.0 of the gradle plugin

### ISSUE THREAD

**Issue by yogurtearl** [nickbutcher/plaid#45]
I tried upgrading to 1.5.0 of the gradle plugin but I got this error: 

Error:Execution failed for task ':bypass:transformNative_libsWithSyncJniLibsForRelease'.
> java.io.FileNotFoundException: /Users/......./GIT/plaid/third_party/bypass/build/intermediates/bundles/release/jni/lib/arm64-v8a/libbypass.so (No such file or directory)

**Comment by nickbutcher** [comment]
Indeed :( 

I'm tracking this: https://code.google.com/p/android/issues/detail?id=193063

**Comment by randhika** [comment]
Same issue..
how to solve this?

**Comment by nickbutcher** [comment]
I don't have a resolution yet which is why i'm still using gradle plugin 1.3.1.  I'm tracking the above issue waiting for the Tools team to investigate.

**Comment by yogurtearl** [comment]
@nickbutcher FYI, "Priority-Small" on the referenced ticket. maybe you can get them to bump up the priority
