### ISSUE TITLE
Up arrow after search item is selected is squished

### ISSUE THREAD

**Issue by ddukesterman** [nickbutcher/plaid#46]
I'm using a Note 3 on Sprint running 5.0. When you press the search button in the toolbar the up arrow becomes squished after the animation.

![image](https://cloud.githubusercontent.com/assets/3778517/11480064/0a0eba44-975b-11e5-9201-ac1c0d423fcb.png)

**Comment by skynet67** [comment]
Same thing on Samsung s4. And a few more animation issues.

![device-2015-12-01-115649](https://cloud.githubusercontent.com/assets/1792357/11497623/d02b4e6e-9822-11e5-950a-85d7d6a66daa.png)

**Comment by nickbutcher** [comment]
@skynet67 your second issue sounds like a dupe of #2.  Closing this issue, please can you add any further info to the existing issue? Thanks!
