### ISSUE TITLE
Parsing on `description` in DribbbleSearchConverter is very vague.

### ISSUE THREAD

**Issue by XinyueZ** [nickbutcher/plaid#497]
https://github.com/nickbutcher/plaid/blob/d355ed8c93ce40c695e248d8f621ed0b407b2bd0/core/src/main/java/io/plaidapp/core/dribbble/data/search/DribbbleSearchConverter.kt#L65

The compiler thinks that the `description` must be `string`.
However, the next line means that it must be `string?`.
https://github.com/nickbutcher/plaid/blob/d355ed8c93ce40c695e248d8f621ed0b407b2bd0/core/src/main/java/io/plaidapp/core/dribbble/data/search/DribbbleSearchConverter.kt#L66

Confused. 😞

**Comment by ataulm** [comment]
https://kotlinlang.org/docs/reference/extensions.html#nullable-receiver

if it's non-null for sure, the next line could be reduced to `if (!description.isEmpty()) {`

**Comment by XinyueZ** [comment]
@ataulm I'm glad to have this contract that the `description`  is 100% nonnull. Could you ship a PR for this improvement?

**Comment by ataulm** [comment]
:+1: I'll avoid for now - it doesn't seem to be a project priority given the notice on the project readme so I'm wary of the overhead.

I'm sure if this class is touched while working on the objectives, the maintainers will look to fix warnings as they go :relaxed:

**Comment by XinyueZ** [comment]
I think that the maintainers would take more focus on main and high priority features rather than these. We can at least help them deal with these low priority trifles, by the way, it can let people easily understand this project and improve the Kotlin-skill.
