### ISSUE TITLE
Backward Compatibility Request

### ISSUE THREAD

**Issue by niteshkhatri** [nickbutcher/plaid#50]
Hey. First of all I want to thank you for open sourcing such a beautiful masterpiece. I loved everything about Plaid. I love the transitions, animations, UI designing and everything. Your project will help a lot of designers and developers to build better apps. Also, Nice use of light status bar.

I am requesting you to kindly make this app backward compatible. I know there are things you have used which are not possible prior Lollipop. Still I would love to see this app in pre-Lollipop devices.

I would really appreciate that.

**Comment by nickbutcher** [comment]
Thank you for your kind words. I'm definitely interested in backporting but it isn't the highest priority on my backlog right now.  Read more here: https://github.com/nickbutcher/plaid/issues/47#issuecomment-160945641
