### ISSUE TITLE
 Not sure if it is a bug

### ISSUE THREAD

**Issue by LcxAndroidwawa** [nickbutcher/plaid#516]
Run the application Click on the item to flash directly  Didn't find class "io.plaidapp.dribbble.ui.shot.ShotActivity"

**Comment by ataulm** [comment]
Hello! Thanks for the report.

Did you build this with Android Studio or via the command line? If using AS, please note the minimum supported version is 3.2 (RC3 is available in the beta channel).

**Comment by LcxAndroidwawa** [comment]
well, thanks for your reminder,  My As version is 3.0, this issue could close
