### ISSUE TITLE
Change `safeApiCall` params order

### ISSUE THREAD

**Issue by mlegy** [nickbutcher/plaid#521]
Would you accept a PR to make safeApiCall
` safeApiCall(errorMessage: String, call: suspend () -> Result<T>)`
instead of ` safeApiCall(call: suspend () -> Result<T>, errorMessage: String)` so that the `call` param  can be placed outside the parentheses? 

example of usage:
```kotlin
suspend fun getComments(ids: List<Long>) = safeApiCall(errorMessage = "Error getting comments") {
    requestGetComments(ids)
}
```

**Comment by qwertyfinger** [comment]
Florina [replied](https://www.youtube.com/watch?v=Sy6ZdgqrQp0&lc=UgxX0niQUjbxlkX1cKZ4AaABAg.8m0cL0mIbTH8mBKvVifjKB) to the same suggestion in the comments on her KotlinConf talk about Plaid 2.0:

> We didn't like how it looked by putting first what should happen in case of error, and only then to put the call, which was the most important thing from that function.﻿

**Comment by florina-muntenescu** [comment]
The error shouldn't be the most important thing there, but rather the call!

**Comment by JoaquimLey** [comment]
I'm aware this is very old, but if you don't handle the message here, or simply want to upstream exception message, which in my case I let the upper layer handle the user-facing error you can do something long these lines:

```kotlin

suspend fun <T : Any> safeApiCall(
    errorMessage: String? = null,
    call: suspend () -> Result<T>
): Result<T> {
    return try {
        call()
    } catch (e: Exception) {
        // An exception was thrown when calling the API so we're converting this to an IOException
        Result.Error(errorMessage ?: e.localizedMessage)
    }
}

```

As debated the error isn't the most important thing, but in this case, for future readers reaching this issue, this could help you. In my project, I have and use both _versions_.
