### ISSUE TITLE
Unable to build project in Android Studio 3.3

### ISSUE THREAD

**Issue by IgorGanapolsky** [nickbutcher/plaid#525]
I am trying to build the project in A.S. 3.3 Canary 13.  It errors out with:
> Configure project :app
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
CONFIGURE SUCCESSFUL in 4s
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.0.3.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve android.arch.lifecycle:common:1.0.3.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve com.android.support:support-annotations:26.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve android.arch.core:common:1.0.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve com.android.support:support-core-utils:26.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve com.android.support:support-compat:26.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.0.3.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve com.android.support:support-core-utils:26.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve com.android.support:support-annotations:27.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve com.android.support:support-compat:27.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve com.android.support:support-compat:27.1.1.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve com.android.support:support-annotations:27.1.1.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve com.android.support:support-core-utils:27.1.1.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve com.android.support:support-annotations:26.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.1.1.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve android.arch.core:common:1.1.1.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve android.arch.lifecycle:common:1.1.1.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@debug/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@release/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.0.3.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@release/compileClasspath': Could not resolve android.arch.lifecycle:common:1.0.3.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@release/compileClasspath': Could not resolve com.android.support:support-annotations:26.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@release/compileClasspath': Could not resolve android.arch.core:common:1.0.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@release/compileClasspath': Could not resolve com.android.support:support-core-utils:26.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@release/compileClasspath': Could not resolve com.android.support:support-compat:26.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@release/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.0.3.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@release/compileClasspath': Could not resolve com.android.support:support-core-utils:26.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@release/compileClasspath': Could not resolve com.android.support:support-annotations:27.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@release/compileClasspath': Could not resolve com.android.support:support-compat:27.1.0.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@release/compileClasspath': Could not resolve com.android.support:support-compat:27.1.1.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@release/compileClasspath': Could not resolve com.android.support:support-annotations:27.1.1.
Show Details
Affected Modules: designernews
ERROR: Unable to resolve dependency for ':designernews@release/compileClasspath': Could not resolve com.android.support:support-core-utils:27.1.1.
Show Details
Affected Modules: designernews

Any ideas?

**Comment by amrro** [comment]
Hey @IgorGanapolsky. This 358e6ba560b974f4afddae36070f3a99cc5f9228 might solve it.

**Comment by IgorGanapolsky** [comment]
@amrro The latest commit seems to fix the issue
