### ISSUE TITLE
Plugin [id: 'com.diffplug.gradle.spotless', version: '3.14.0'] was not found

### ISSUE THREAD

**Issue by muzammilhussnain14** [nickbutcher/plaid#548]
> Plugin [id: 'com.diffplug.gradle.spotless', version: '3.14.0'] was not found in any of the following sources:

> - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> - Plugin Repositories (could not resolve plugin artifact 'com.diffplug.gradle.spotless:com.diffplug.gradle.spotless.gradle.plugin:3.14.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

**Comment by ataulm** [comment]
Do you have the latest copy of master? The project syncs fine for me.

**Comment by muzammilhussnain14** [comment]
> Do you have the latest copy of master? The project syncs fine for me.

Yes I pulled fresh copy of master yesterday and wasn't able to compile the code. 
Thanks fro reply.

**Comment by ataulm** [comment]
It's a little weird since `3.14.0` is [available on Gradle Central Plugin Repository](https://plugins.gradle.org/plugin/com.diffplug.gradle.spotless/3.14.0) (latest is 3.16.0).

Can you run `./gradlew spotlessApply` from a terminal?

**Comment by muzammilhussnain14** [comment]
I updated on following two places which fixed the error for me.
`classpath 'com.android.tools.build:gradle:3.3.0-beta02'`
**TO**
`classpath 'com.android.tools.build:gradle:3.4.0-alpha02'`
and : 
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-bin.zip`
**TO**
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`

which fixed the issue for me. Thanks @ataulm

**Comment by ataulm** [comment]
:+1: glad it's resolved but I don't think I helped 😅

If you're able, please close this issue 😊
