### ISSUE TITLE
Questing about Filterable

### ISSUE THREAD

**Issue by Orbyt** [nickbutcher/plaid#55]
@nickbutcher Asked you about this on twitter but you requested more info as a Github issue so:

In Plaid the drawer items can be selected and deselected to filter out items in the main grid. I noticed that for this, you chose to build your own filtering system, instead of using `Filterable` by implementing it in the grids adapter class. I was curious as to why?

**Comment by nickbutcher** [comment]
Hi @Orbyt, do you mean  `android.widget.Filterable`? `RecyclerView.Adapter` does not have built in Filtering.

**Comment by Orbyt** [comment]
@nickbutcher Yep. I had been looking into implementing a filter and most of the examples on SO seemed to make use of `Filterable`, but I noticed the filtering system in Plaid does not, so was just wondering if there was a particular reason.
