### ISSUE TITLE
the item of list 

### ISSUE THREAD

**Issue by whataa** [nickbutcher/plaid#57]
![screenshot_20160117-220909](https://cloud.githubusercontent.com/assets/10238308/12377877/29f303ba-bd67-11e5-838e-7a97de843cb1.png)

**Comment by nickbutcher** [comment]
Please can you provide more information, do you have steps to reliably recreate this?

**Comment by whataa** [comment]
No step can recreate this situation, I guess it may be due to network，my phone is nexus 5, android 6.0. 
But now I found another more serious problem that can cause the app to stop running, When you drag the list up or down quicklyt, repeat this action several times, and then ,the problem comes out.

**Comment by whataa** [comment]
@nickbutcher

**Comment by nickbutcher** [comment]
I'm not able to repro any of these issues so am closing this issue.  Please do re-open if you have repeatable steps.
