### ISSUE TITLE
API keys in gradle.properties

### ISSUE THREAD

**Issue by ataulm** [nickbutcher/plaid#584]
On other projects, I use a [build properties plugin](https://github.com/novoda/gradle-build-properties-plugin) to keep keys in separate files, and I add these to the `.gitignore`:

https://github.com/ataulm/art-collector/blob/master/app/build.gradle#L7..L14

I've replaced the values in gradle.properties but I need to remember to avoid staging it because in Plaid, `gradle.properties` is tracked by git.

Is there some way to avoid tracking local changes to this file explicitly? Or do you just remember not to commit it? 🤔

**Comment by florina-muntenescu** [comment]
We keep the keys in the global properties, not in the project properties. Therefore, we don't have the commit issue.

**Comment by ataulm** [comment]
Thanks! The project one has placeholders so I assumed they were being
replaced but I guess the global ones override
