### ISSUE TITLE
found error: Cause: org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;

### ISSUE THREAD

**Issue by poel** [nickbutcher/plaid#588]
When I import the project into android studio and compile, found error: 
Cause:org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;

**Comment by poel** [comment]
My android studio version is : 3.2.1

**Comment by ataulm** [comment]
Hi @poel, thanks for the report.

I see the README still says that Plaid requires 3.2 or above, but I think that's outdated - it's using an alpha version of the Android Gradle Plugin which requires using AS 3.4 canaries if you want to build with AS (command-line builds should be fine).

I think they'd appreciate a PR to update the README if you learn which version specifically if necessary.

**Comment by poel** [comment]
@ataulm Thanks for your feedback. I will update my AS to 3.4.

**Comment by poel** [comment]
@ataulm I had update my AS to 3.4 and had run the project successfully! Thanks.
