### ISSUE TITLE
latest update broke toolbar menu items

### ISSUE THREAD

**Issue by k0shk0sh** [nickbutcher/plaid#59]
As the title says, latest update broke the toolbar menu items, they are not clickable i thought you disabled them until.i swipe out the navigation menu manually instead of the menu item and it works which leads that there is something wrong with the menu items. 
Im using Lollipop, galaxy s6 edge  if that helps.

**Comment by nickbutcher** [comment]
Strange, works fine on my test devices.  I'll see if I can get hold of a SGS6e to repro.

**Comment by nickbutcher** [comment]
Ah, think i've managed to repro it. Fix incoming.

**Comment by k0shk0sh** [comment]
Okay cool, thanks.

Best Regards,
Kosh
