### ISSUE TITLE
Failed to notify build listener

### ISSUE THREAD

**Issue by s949492225** [nickbutcher/plaid#599]

**Comment by ataulm** [comment]
Is this in the IDE when syncing or via the command line?

If it's IDE, what version do you use?
If it's command line, what command are you running?

**Comment by s949492225** [comment]
androidStudio 3.2

**Comment by ataulm** [comment]
Please update to 3.4. You need at least the version matching the Android Gradle Plugin which is probably 9 or 10.

**Comment by s949492225** [comment]
ok,thanks
