### ISSUE TITLE
Update the About screen to use the ViewPager2 library

### ISSUE THREAD

**Issue by florina-muntenescu** [nickbutcher/plaid#618]
We have a special request here: if you're taking on this issue, please give us feedback about your experience of migrating from `ViewPager` to `ViewPager2` - from the steps you took, to the issues you've encountered when working with the `ViewPager2` API. 
We'd like to use this information to improve the user experience with the API.

Thank you!

**Comment by arangob** [comment]
opened pull request #620

**Comment by florina-muntenescu** [comment]
Thanks @arangob !
