### ISSUE TITLE
Not able to install the beta app

### ISSUE THREAD

**Issue by manyata** [nickbutcher/plaid#65]
After becoming a tester, i am trying to follow the link to download the app, but i keep getting the error "We're sorry, the requested URL was not found on this server." 
![screen shot 2016-02-19 at 11 50 35](https://cloud.githubusercontent.com/assets/3773711/13168055/04b6297c-d6ff-11e5-82be-4bcb7505fb48.png)

**Comment by nickbutcher** [comment]
Hullo, it can take a little time after becoming a tester for the app to be available on the store.  Please can you try again and re-open if you're still having problems? Thanks!

**Comment by manyata** [comment]
Still facing the same problem...

**Comment by nickbutcher** [comment]
Strange. Are you definitely using the same account to access the app in the
Play Store as you signed up for the beta with?

**Comment by manyata** [comment]
got it. that was the issue. Multiple google accounts on chrome! :)  thanks
