### ISSUE TITLE
Loading bar issue when no internet

### ISSUE THREAD

**Issue by ashishbhandari** [nickbutcher/plaid#66]
![screenshot_2016-02-19-12-50-09](https://cloud.githubusercontent.com/assets/578901/13170766/e7f78c14-d707-11e5-8d7b-49938131c2de.png)

**Comment by nickbutcher** [comment]
Can replicate if you are offline and then toggle a feed.  Thanks for the bug report.

**Comment by nickbutcher** [comment]
Should be fixed in the next update.
