### ISSUE TITLE
Network connected again when it was not connected before,the no connection image was still there.

### ISSUE THREAD

**Issue by JohnTsaiAndroid** [nickbutcher/plaid#67]
![qq20160222-0](https://cloud.githubusercontent.com/assets/8317477/13208634/c6072768-d955-11e5-8cd2-d9f353fbc0ae.png)

In my view,we can add a onclicklistener with the viewStub.When the network connected again,the recyclerview replace the viewStub.

**Comment by nickbutcher** [comment]
Thanks for the bug report.  Should be fixed in the next build.
