### ISSUE TITLE
Pressing on "Dribble following" shows an empty popup

### ISSUE THREAD

**Issue by qmar** [nickbutcher/plaid#7]
Phone: LG G2, Android 5.0.1

Steps to reproduce:
1. Open app
2. Press on the "three horizontal lines button" in actionbar to show right menu
3. Press on "Dribble following"

Same happens for: "My dribble shots" and "My dribble likes"

![empty_popup](https://cloud.githubusercontent.com/assets/2963232/10864417/cd764a9a-7fed-11e5-9fc2-ef54686d1914.png)

**Comment by nickbutcher** [comment]
I believe that this is an issue with Lollipop as the same transition works fine on newer devices. Unlikely to fix.
