### ISSUE TITLE
Failed to apply plugin

### ISSUE THREAD

**Issue by ogapants** [nickbutcher/plaid#72]
I got this error:

```
Error:(17, 1) A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Gradle version 2.10 is required. Current version is 2.8. If using the gradle wrapper, try editing the distributionUrl in .../plaid/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip
```

However, it has been resolved in 'backport' branch. 
https://github.com/nickbutcher/plaid/commit/bbb969492cae9cae32347b28418d59777215c22a

I hasten to report because it could not build.

**Comment by nickbutcher** [comment]
Fixed in 7878696d2f6506badcb61b719fdce716c97bcf8f thanks!
