### ISSUE TITLE
`player` and `dataManager` variables can be null and it causes the app to crash

### ISSUE THREAD

**Issue by amilcar-andrade** [nickbutcher/plaid#84]

**Comment by amilcar-andrade** [comment]
This PR (https://github.com/nickbutcher/plaid/pull/83) addressed the issue.

**Comment by amilcar-andrade** [comment]
Attached are some videos showing the previous and new behavior.


![player_act](https://cloud.githubusercontent.com/assets/802308/14536717/c75c2720-0241-11e6-8963-062d793c47c7.gif)
![player_act_crash](https://cloud.githubusercontent.com/assets/802308/14536718/c75d9704-0241-11e6-8481-45e202d80aa6.gif)

**Comment by nickbutcher** [comment]
Thanks for the pull resolving this!
