### ISSUE TITLE
Question: generating vector-drawable pathData?

### ISSUE THREAD

**Issue by lucamtudor** [nickbutcher/plaid#94]
I've studied the `avd_upload_*` animated-vector-drawables and I'm curious how do you generate your vector's pathData? Sketch? 
For example, [ic_upload_complete](https://github.com/nickbutcher/plaid/blob/master/app/src/main/res/drawable/ic_upload_complete.xml#L32) doesn't look like it's written by hand 👍 .

**Comment by nickbutcher** [comment]
Some paths are straight from the material icon set. Others (like that one) I do indeed draw by hand in Sketch, export as SVG and use the Android Studio importer (or sometimes just copy paste the `pathData`) to create the VectorDrawable.
