### ISSUE TITLE
Can't install the app with Chinese language using

### ISSUE THREAD

**Issue by TimmySong** [nickbutcher/plaid#95]
I can not find the app through 'Plaid' keyword searching in Google Play. Then installment through PC Google Play still failed because of error code 940(Tip on handheld device: Content not found). Then I guess it maybe language configuration related issue. After change device language to English, I can search the result and install it. I think this may be a problem:)
(Ps: Attempt to send e-mail to support@plaidapp.io failed too through gmail. It's really weird.)

**Comment by rabyunghwa** [comment]
It's not an issue. It's the policy. Google Play has [Country Restrictions](http://www.android.gs/how-to-modify-the-google-play-store-to-remove-country-restrictions/). And it's great that you found a solution. :+1:

**Comment by TimmySong** [comment]
Got it :)
