### ISSUE TITLE
Searchbox textfield overlapped with the back actionbar button

### ISSUE THREAD

**Issue by LouisCAD** [nickbutcher/plaid#96]
Hi!
The title and the screenshot are self-explanatory!
I saw this on my Nexus 6P running Android N Preview 4, with display density set to small.

![screenshot_20160618-163331](https://cloud.githubusercontent.com/assets/6975237/16171629/fc5ead02-3573-11e6-9e68-d19a9688c322.png)

Have a nice day, and thanks for your work and your talk at I/O 2016!

**Comment by nickbutcher** [comment]
Thanks for the bug report & glad you enjoyed the talk!
