### ISSUE TITLE
Multiline title breaks details screen

### ISSUE THREAD

**Issue by mpost** [nickbutcher/plaid#98]
The screenshot bellow shows the problem

![device-2016-07-06-173044](https://cloud.githubusercontent.com/assets/73655/16623792/80823d0e-439f-11e6-9b0d-42a8c087fe3d.png)

**Comment by nickbutcher** [comment]
Thanks for the issue report. Please can you provide more info about your device configuration? Multiline titles work fine for me on all test devices; that exact image displays correctly for me.

**Comment by mpost** [comment]
The device was a galaxy s6

**Comment by nickbutcher** [comment]
Still haven't been able to replicate but had another report (#120). Must be a bug lurking in `FabOverlapTextView`. I'll try and find some time to look at it.
