### ISSUE TITLE
how to use ElasticDragDismissFrameLayout with Webview

### ISSUE THREAD

**Issue by phirumtan** [nickbutcher/plaid#99]
![edit_device-2016-07-06](https://cloud.githubusercontent.com/assets/14540500/16625634/bd52ca98-43cf-11e6-8c6d-11e750429457.png)

In this screenshot contain with header and content of listview.
the problem is i can't replace Listview with Webview.
i try to implement a lot of time but can't do it.
Please help me.

Thank for advance.

**Comment by nickbutcher** [comment]
`ElasticDragDismissFrameLayout` is built on top of nested scrolling – it relies on this to get the scrolls from the nested child. I'm not sure if `WebView` acts as a nested scrolling child; you can check if `ElasticDragDismissFrameLayout#onStartNestedScroll` is called when you swap `ListView` for a `WebView`.

Closing this issue as it's not related to Plaid itself. Good luck!

**Comment by phirumtan** [comment]
Thank you
